### ISSUE TITLE
WooCommerce Templates out of date

### ISSUE THREAD

**Issue by kawhatley** [understrap/understrap#1903]
Could you please update the woocommerce templates in your parent and child theme? With the latest version of woo, they are now out of date.

<img width="397" alt="understrap-woo update" src="https://user-images.githubusercontent.com/13318013/190186066-7c2c65c9-f64a-4272-bf9c-ebdca938384f.PNG">

**Comment by bacoords** [comment]
Thank you for the heads up. Adding this to our queue.

**Comment by paulhaskett** [comment]
I'm also getting this error on many template files since updating woocommerce, thanks

**Comment by IanDelMar** [comment]
@bacoords fixed in v1.2.0

**Comment by paulhaskett** [comment]
I'm still getting errors 
![image](https://user-images.githubusercontent.com/14015669/202895426-b6021eea-e7d1-408c-8ca0-9385fb4acaab.png)

**Comment by bacoords** [comment]
The templates were updated again after we released the beta for this release. We're planning a quicker release here: https://github.com/understrap/understrap/pull/1998
