### ISSUE TITLE
Translation : understrap, understrap-child -> woocommerce

### ISSUE THREAD

**Issue by Podtwal** [understrap/understrap#838]
## Issue is about..
  - [x ] a Question

## Please tell us about your environment:

  - **WordPress Version:** 4.9.8
  - **OS Version:** [ Windows 10]
  - **Browser:** [ all]
  - **understrap and understrap-child**

---

Hello.
I have the phenomenon that my woocommerce shop is displayed linguistically "mixed" (DE/EN) in the FE (e.g. "Proceed to checkout", but also more) -> both at understrap, as well as at understrap-child. For example, if I switch to twentyseventeen, everything fits.

In the language directory of understrap and here in the DE translation the term "Proceed to checkout" is also correctly translated... only in the FE it is not output.

What am I doing wrong???

**Comment by Podtwal** [comment]
Apparently there's been something here before:
- https://github.com/understrap/understrap/issues/691

I deleted the file "proceed-to-checkout-button.php" from the server in understrap/woocommerce/cart/ and reloaded the FE.
The translation was correct afterwards.

What to do? Is there a bug in understrap?

**Comment by codearosa** [comment]
I have the same issue.

### Please tell us about your environment:

- WordPress Version: 5.1.1
- OS Version: [ Windows 7]
- Browser: [ all]
- understrap and understrap-child
- woocommerce germanized

I did same as @Podtwal but nothing changed.
What I am doing wrong?

**Comment by codearosa** [comment]
Right:

`<a href="<?php echo esc_url( wc_get_checkout_url() ); ?>" class="btn btn-primary btn-lg btn-block">
	<?php esc_html_e( 'Proceed to checkout', 'woocommerce' ); ?>
</a>`


But that is:

`<a href="<?php echo esc_url( wc_get_checkout_url() ); ?>" class="btn btn-primary btn-lg btn-block">
	<?php esc_html_e( 'Proceed to checkout', 'understrap' ); ?>
</a>`

**Comment by codearosa** [comment]
Bug found:

old woocommerce template files in understrap

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.

**Comment by gaelgerard** [comment]
Hi all, I re open this subject as the problem is not fixed.

I faced the same problem of mixed translation in Woocommerce (FR/EN)

I found that Woocommerce templates in Understrap were configured to use understrap translations as shown above by @codearosa .

`<a href="<?php echo esc_url( wc_get_checkout_url() ); ?>" class="btn btn-primary btn-lg btn-block"> <?php esc_html_e( 'Proceed to checkout', 'understrap' ); ?> </a>`

But lots of Woocommerce Strings aren't (yet?) translated in Understrap pot files.

To solve my problem, I copied Woocommerce directory from Understrap to my child theme and replaced every 'understrap' declaration with initial 'woocommerce' ones.

`<a href="<?php echo esc_url( wc_get_checkout_url() ); ?>" class="btn btn-primary btn-lg btn-block"> <?php esc_html_e( 'Proceed to checkout', 'woocommerce' ); ?> </a>`

I think it would be great to keep 'woocommerce' calls in Understrap woocommerce templates as the plugin already uses its own pot file.

**Comment by fero8** [comment]
I have the same issue. Had to as woocommerce already has all the required translations but understrap doesn't. Had to copy all the theme files and replace the domain for each string, which does not seem as a good way to go forward.

I am also wondering how to force my child theme to use woocommerce domain strings rather than understrap? So that I do not have to copy and replace all the domain references in the template files.
